### ISSUE TITLE
[BUG] R installation fails with standard installation procedure due to igraph dependency not found

### ISSUE THREAD

**Issue by marioangst** [latentnetworks/vimure#77]
**Describe the bug**
Installing the R package by following the steps described in https://latentnetworks.github.io/vimure/latest/install.html fails on Windows 11, R 4.1.
vm_config() results in **ModuleNotFoundError: No module named 'igraph'**.
Installing igraph via **reticulate::py_install("igraph",pip = TRUE)** results in the correct outcome.

**To Reproduce**
1. Follow: https://latentnetworks.github.io/vimure/latest/install.html
2. vimure::vm_config() results in **ModuleNotFoundError: No module named 'igraph'**.

**Expected behavior**
vimure::vm_config() resulting in "Loaded vimure version".

**Environment (please complete the following information):**
 - OS: Windows 11
 - R/Python versions: 4.1/ 3.6

**Additional context**
I could resolve the problem using:
1. reticulate::use_condaenv("r-reticulate")
2. reticulate::py_install("igraph",pip = TRUE)

**Comment by marioangst** [comment]
Ok, the same error is also present when using the Python package on its own (not through the R interface)

**Comment by jonjoncardoso** [comment]
I was able to reproduce the reported bug, and it has now been fixed with https://github.com/latentnetworks/vimure/commit/89dbc7c23feba556f70d906a9829c389651e65fd  and https://github.com/latentnetworks/vimure/commit/26373ce87c314e42414463df7169e4b94b4fb3b5. Feel free to re-open this issue if a clean install still throws an error.
